# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - abdulwahab-web-csv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://abdulwahab-web-csv.azurewebsites.net/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d33f4d058254271b18666fe3886e47d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d080619875774d92afd731f22ce179b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: abdulwahab-web-csv.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_1d33f4d058254271b18666fe3886e47d }}/abdulwahab-web-csv_0_b474241a:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'abdulwahab-web-csv'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b5a5462e45e448d89a62df4110eb7a2 }}
        images: 'abdulwahab-web-csv.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_1d33f4d058254271b18666fe3886e47d }}/abdulwahab-web-csv_0_b474241a:${{ github.sha }}'